name = "aiken-lang/smart-account"
version = "0.0.0"
compiler = "v1.1.2"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/smart-account'"

[repository]
user = "aiken-lang"
project = "smart-account"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[[dependencies]]
name = "aiken-lang/merkle-patricia-forestry"
version = "2.0.0"
source = "github"

[config]
